{% set version = "0.9.1" %}

package:
  name: chemfiles
  version: {{ version }}

build:
  skip: true  # [win and py2k]
  number: 0

requirements:
  run:
    - chemfiles-lib 0.9.*
    - chemfiles-python 0.9.*

test:
  commands:
    # If we can load the python extension and create new object, both the python
    # binding and the shared library are installled in the right place
    - python -c "import chemfiles; chemfiles.Atom('H')"

about:
  home: https://chemfiles.org
  license: BSD-3-Clause
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.org/chemfiles/{{ version }}/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
