{% set version = "0.10.1" %}

package:
  name: chemfiles
  version: {{ version }}

build:
  skip: true  # [(win and py2k) or (python_impl == 'pypy')]
  number: 0

requirements:
  run:
    - chemfiles-lib >=0.10.1,<0.11
    - chemfiles-python >=0.10.1,<0.11

test:
  commands:
    # If we can load the python extension and create new object, both the python
    # binding and the shared library are installed in the right place
    - python -c "import chemfiles; chemfiles.Atom('H')"

about:
  home: https://chemfiles.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.org/chemfiles/{{ version }}/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
