travis:
  secure:
    BINSTAR_TOKEN: oUT4N/ou56B+o5zhfcnOQrrwcNncHvIsx6V5aSEKI9wWCM8CnWDSoDuo0tfwCsrGPjRwSljjBrE9Z5IN6jKVjGY0dZK0jBdsjGtvp3mG9MALL/1OatDPOrjyar9Wl6hLQVcTvmBZUBhu7/HANqHqXavmr7e8TehW5F8YtFRkNK/LWZKiRgN3ldoopW2QKbsC0YP6jG6LshLwAtr5/wxw/AqJeBAbOwY3E0tETGc31j5MYvgjo7yxA0eIwxXYknNiVD0Ch6DMWVJ9uHNUy3xLMMmf59O4liB6nAuhUSH9ouQN6THKyM7LYQWTgDlUEFfYPEW9sYNI/Yf0zt3ceq9RPUoIs5VPJ1hmmwYNi3v01K73XjoJMu9Evs9aGmpeGx7CvCgplPuCZ1AQSgiVP/8y7oYAx+e/SmtGF0MEt7lXUToDWhjSBSpK9i88wSsXl53y4g4tn/xxsiJXH0nOJDkSUNB4pTssJNFh54aKIMII68SdpPlYJbiW7jthIf1SWEIPTV/kSjcwiLBGS5piZ4ofMl34kBB2RDvaHw5gox+iwFDXgHLIv0bbBWdKaLU6EN/usseS8AA11fwhNYL95L42nzNbReX0+A+BPfSky8d6xiQnXywHuysf6nhBI1Rbe+PsWsBryadIuNGIqBL85pi3ux6et6GdvylbAbylTudKM3U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
