travis:
  secure:
    BINSTAR_TOKEN: ay9ckNQF6Mj0NGpoiUUjqxq7k2hDOFkbvh88NpQmp4cTkIYdMT0nZ97vOpjY8O48W1wj2x+cnrrb0uFZlOtGYez3Lp6XZKn8PHGXWSQEKvHu7ootprVWPkyixiyN7Q4ZEXlkAxptQnDIV0w44k40vm4vM7pry/x6VSTNTREMRpR2Qh2Fi/JkA6rDvPw++JrDD6SoROw8B+QhAbP22pPUuOLSCWLBTiJ4cRRGKSeIT+K1YjhZrf6KhbGccoIFhXGGVwg1/O1oCECG9vXBtllj9+ekhdeLoXVn7+SsJDJyPKu9x8iorjF0EV3Qb0jer/sex2GD3+alKHmT2Bb2wo4jCXGB7SnN363zIiTBmyakIm9gmHC8lH0wXY8TsLlnnmicXu5uhfYwzPk0gW7GASLv9MPb6EJ+j5kmxh4eP/9Y/SBZFwPZT4kdrUJQocVXrp80ClU88um5SlKfZELqNYEVBT6eTSyvUp8wVKzAK93W+QJ7GUK7mMEbG+Py3hZfPWOQfagKiKnrIkHFoC0H3kVdjA9L8kbyISz+HmJbNhNG8/b5all6uV8U0OEzARM2G/exEQl02hKCncVIlPhnhSpRTObIsn6O6bQr8S35FTtp5K8NHoXEpMXFPGzIakks6kJ6kmFcCrkZ2dq6gOiUg8hUe6Gs4cE+9VaKyOVdI3mDyJY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
